/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String test = "test";
        String wrong = "";

        if(wrong == test){
            System.out.println("this is test");
        }
        
    }
}
